import { SampleVideo } from '../types';

export const SAMPLE_VIDEOS: SampleVideo[] = [
  {
    id: 'sample-bunny',
    title: 'Big Buck Bunny (Short Film Teaser)',
    description: 'Blender Foundation open animation movie teaser in HD. High detail 3D render.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    duration: '09:56',
    size: '5.5 MB',
    approxBytes: 5767168,
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    category: 'Animation',
  },
  {
    id: 'sample-sintel',
    title: 'Sintel - The Dragon Flight',
    description: 'Fantasy quest following a lonely girl searching for a baby dragon in the snow peaks.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    duration: '00:52',
    size: '6.2 MB',
    approxBytes: 6500000,
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    category: 'Fantasy',
  },
  {
    id: 'sample-tears-of-steel',
    title: 'Tears of Steel (Sci-Fi VFX Breakdown)',
    description: 'Dystopian future Amsterdam robotics VFX film exploring cybernetic neural networks.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    duration: '12:14',
    size: '8.4 MB',
    approxBytes: 8808038,
    thumbnail: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600&auto=format&fit=crop&q=80',
    category: 'Sci-Fi',
  },
  {
    id: 'sample-escape',
    title: 'For Bigger Escape (Nature & Adventure)',
    description: 'Dynamic outdoor cinematic footage showcasing mountain biking and trail expeditions.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration: '00:15',
    size: '2.4 MB',
    approxBytes: 2516582,
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
    category: 'Adventure',
  },
  {
    id: 'sample-blazes',
    title: 'For Bigger Blazes (Action Reel)',
    description: 'Fast-paced action sports sequence highlighting 60fps high dynamic range capture.',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration: '00:15',
    size: '2.1 MB',
    approxBytes: 2202009,
    thumbnail: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=600&auto=format&fit=crop&q=80',
    category: 'Sports',
  },
];
